# Generated by Django 3.2.3 on 2021-06-20 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210615_1233'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('favourite_id', models.AutoField(primary_key=True, serialize=False)),
                ('touristic_place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.touristicplace')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
