# Generated by Django 3.2.3 on 2021-06-28 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_category_touristicplacecategory'),
        ('users', '0002_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceCategory',
            fields=[
                ('preference_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.category')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
