# Generated by Django 3.2.3 on 2021-07-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_ranking_touristicplace_avg_ranking'),
        ('users', '0003_preferencecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencecategory',
            name='picture',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.CreateModel(
            name='PreferenceTypePlace',
            fields=[
                ('preference_typeplace_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(default='None', max_length=255)),
                ('type_place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.typeplace')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
