# Generated by Django 3.2.3 on 2021-07-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210702_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencecategory',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='preferencetypeplace',
            name='picture',
        ),
    ]
