# Generated by Django 3.2.3 on 2021-08-25 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_subcategory'),
        ('users', '0006_auto_20210702_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceSubCategory',
            fields=[
                ('preference_subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.subcategory')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
