# Generated by Django 3.2.3 on 2021-08-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_preferencesubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
