# Generated by Django 3.2.3 on 2021-06-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureReview',
            fields=[
                ('preview_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('comment_ranking', models.IntegerField()),
                ('date', models.DateField(default='2021-08-16')),
                ('ranking', models.IntegerField()),
                ('touristic_place', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='places.touristicplace')),
            ],
        ),
    ]
