# Generated by Django 3.2.3 on 2021-07-01 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_ranking_touristicplace_avg_ranking'),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='touristic_place',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='places.touristicplace'),
        ),
    ]
