# Generated by Django 3.2.3 on 2021-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_touristic_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturereview',
            name='image',
            field=models.ImageField(default=4, upload_to='', verbose_name='image'),
            preserve_default=False,
        ),
    ]
