# Generated by Django 3.2.3 on 2021-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristicplace',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='touristicplace',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
