# Generated by Django 3.2.3 on 2021-06-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210615_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristicplace',
            old_name='range',
            new_name='tp_range',
        ),
    ]
