# Generated by Django 3.2.3 on 2021-06-28 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_range_touristicplace_tp_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TouristicPlaceCategory',
            fields=[
                ('tp_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.category')),
                ('touristic_place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='places.touristicplace')),
            ],
        ),
    ]
