# Generated by Django 3.2.3 on 2021-06-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210531_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristicplace',
            old_name='historic',
            new_name='historic_info',
        ),
        migrations.RenameField(
            model_name='touristicplace',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
