# Generated by Django 3.2.3 on 2021-06-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_category_touristicplacecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicplace',
            name='ranking',
            field=models.FloatField(default=0.0),
        ),
    ]
