# Generated by Django 3.2.3 on 2021-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210531_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturetouristicplace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
