# Generated by Django 3.2.3 on 2021-06-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_touristicplace_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicplace',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
    ]
