# Generated by Django 3.2.3 on 2021-07-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_touristicplace_number_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristicplace',
            old_name='ranking',
            new_name='avg_ranking',
        ),
    ]
