# Generated by Django 3.2.3 on 2021-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_ranking_touristicplace_avg_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
