# Generated by Django 3.2.3 on 2021-07-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='province',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
