# Generated by Django 3.2.3 on 2021-07-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20210703_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristicplace',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
